# Generated by Django 2.2.5 on 2019-09-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='email',
        ),
    ]
